version: "3.8"
services:

  app_web:
    build: ./PracticaJMS
    image: diegobenitez15/jms_server
    ports:
      - ${PORT_APP}:8080
    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - spring.activemq.broker-url=tcp://activemq:61616
    networks:
      - red-app
    volumes:
      - volume-compose:${VOLUME_DB}
    depends_on:
      - activemq
      - database

  client_app:
    build: ./client
    image: diegobenitez15/jms_client
    ports:
      - ${APP_CLIENT_PORT}:61616
    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
    networks:
      - red-app
    depends_on:
      - activemq
      - app_web

  database:
    image:
      buildo/h2database
    ports:
      - ${PORT_DATABASE}:8082
    env_file:
      - .env
    volumes:
      - ~/dato_mysql_compose:/var/lib/mysql
      - volume:${VOLUME_DB}
    networks:
      - red-app

  activemq:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
    container_name: activemq
    networks:
      - red-app

networks:
  red-app:

volumes:
  volume-compose:
  volume: