# Generated by Django 4.1.7 on 2023-04-17 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(choices=[('firma', 'FIRMA'), ('texto', 'TEXTO'), ('otro', 'OTRO CHEQUE')], default='firma', max_length=50)),
                ('image1', models.ImageField(null=True, upload_to='images')),
                ('image2', models.ImageField(null=True, upload_to='images')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
